name: expandable
description: A Flutter widget that can be expanded or collapsed by clicking on a header or an icon.
version: 3.0.0+1
author: Alexander Ryzhov <aryzhov07@gmail.com>
homepage: https://github.com/aryzhov/flutter-expandable

environment:
  sdk: ">=2.3.0-dev.0.5.flutter-a1668566e5 < 3.0.0"
  flutter: "^1.5.0"

dependencies:
  flutter_web:
  flutter_web_ui:

#dev_dependencies:
#  build_runner: any
#
dependency_overrides:
  flutter_web:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web
  flutter_web_ui:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_ui
